packages:
  - "packages/*"

linkWorkspacePackages: false
saveWorkspaceProtocol: rolling
savePrefix: ""
sharedWorkspaceLockfile: true
disallowWorkspaceCycles: true

autoInstallPeers: false
strictPeerDependencies: true
engineStrict: true
