export const CORE_PACKAGE_NAME = "@agent-design-system-kit/core" as const;

export type CorePackageName = typeof CORE_PACKAGE_NAME;

export * from "./approval-record.js";
export * from "./button-contract.js";
export * from "./canonical-json.js";
export * from "./component-change-request.js";
export * from "./component-contract.js";
export * from "./component-query.js";
export * from "./component-audit.js";
export * from "./component-registry.js";
export * from "./design-system-snapshot.js";
export * from "./design-asset-query.js";
export * from "./design-brief.js";
export * from "./direction-review.js";
export * from "./errors.js";
export * from "./figma-variable-plan.js";
export * from "./icon-contract.js";
export * from "./input-contract.js";
export * from "./figma-button-plan.js";
export * from "./figma-button-instance-plan.js";
export * from "./figma-icon-plan.js";
export * from "./figma-icon-instance-plan.js";
export * from "./json.js";
export * from "./logging.js";
export * from "./results.js";
export * from "./registry-drift-audit.js";
export * from "./security.js";
export * from "./semantic-version.js";
export * from "./style-audit.js";
export * from "./schema-primitives.js";
export * from "./schema-validation.js";
export * from "./token-set.js";
export * from "./version.js";
export * from "./writer-protocol.js";
